version: '3.5'
services:
  configure:
    image: registry.cn-qingdao.aliyuncs.com/limes-cloud/configure
    container_name: configure
    restart: always
    network_mode: host
    volumes:
      - ./tmp:/go/build/tmp
      - ./conf:/go/build/internal/conf