version: '3.5'
services:
  configure:
    image: limescloud/configure
    container_name: configure
    restart: always
    network_mode: host
    volumes:
      - ./tmp:/go/build/tmp
      - ./config:/go/build/internal/config